### ISSUE TITLE
Can't compile in Xojo 2017R3

### ISSUE THREAD

**Issue by PabloGringo** [gkjpettet/maebh-cli#2] opened 2018-03-23 15:55 UTC
Dear Garry,

Today finally i found some time to download your Maebh tool.
I really liked the concept when I saw this upload a couple of months ago.

When I compile the sources, i get 2 errors:

Both have me baffled:

1. In method[SetBinaryPaths] Item does not exist.
`  MD5.md5Path = "md5"
`

Which is strange because I see the property in the module MD5

2. MD5.Name - Redefined identifier. This name is already defined by class MD5

I tried several different things, including rebooting my Mac.
But nothing solved this so far.

Can you give me any tips on what to do about this?

Kind regards,
Paul

**Comment by PabloGringo** [comment] 2018-03-26 09:42
Dear Gary,

I have found that the problem mentioned above doesn't happen in Xojo 2017R2,
but i does happen in  Xojo 2017R3.

I will keep you posted on anything else i find.

**Comment by gkjpettet** [comment] 2018-06-26 15:44
Closing as I can't reproduce the issue in Xojo 2018 r1.1.

**Closed by gkjpettet** 2018-06-26 15:44 UTC
